#!/bin/sh
# SPDX-FileCopyrightText: 2023 sublipri <sublipri@proton.me>
# SPDX-License-Identifier: GPL-3.0-only

cat <<EOF
Content-Type: text/html; charset=utf-8
Cache-Control: no-cache

<!doctype html>
<html>
  <head>
	<meta name="viewport" content="width=device-width", initial-scale="1" charset="UTF-8">
	<link href="/styles/main.css" rel="stylesheet" />
	<title>Kobo Wi-Fi Remote</title>
  </head>
  <body>
	<p>$1</p>
	<p><a href="javascript:history.back()"><button "type=button">Go Back</button></a></p>
	</div>
  </body>
  $2
</html>
EOF
